# Generated by Django 2.0.7 on 2018-09-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180921_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
