# Generated by Django 2.0.7 on 2018-09-21 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_is_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_tag',
            new_name='virtual_bank',
        ),
    ]
