# Generated by Django 2.0.7 on 2018-09-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_icons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icons',
            new_name='Icon',
        ),
    ]
