# Generated by Django 2.2.dev20180901131418 on 2018-09-22 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20180921_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='virtualbankaccount',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Icon'),
        ),
        migrations.CreateModel(
            name='SharingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BankAccount')),
                ('sharing_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SharingGroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharingSpending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('paying_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SharingUser')),
                ('sharing_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SharingGroup')),
            ],
        ),
    ]
