# Generated by Django 2.0.7 on 2018-09-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180922_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='virtual_bank',
        ),
        migrations.AddField(
            model_name='icon',
            name='avg_output',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='virtualbankaccount',
            name='money_added_month',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='virtualbankaccount',
            name='money_sub_month',
            field=models.FloatField(default=0.0),
        ),
    ]
