# Generated by Django 2.0.7 on 2018-09-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transaction_virtual_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='money_sub_month',
            field=models.FloatField(default=0.0),
        ),
    ]
