# Generated by Django 2.0.7 on 2018-09-22 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_bankaccount_money_sub_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Icon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tagindex',
            unique_together={('iban', 'user')},
        ),
    ]
