# Generated by Django 2.0.7 on 2018-09-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180922_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='money_in_last_month',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='money_out_last_month',
            field=models.FloatField(default=1000.0),
        ),
    ]
