# Generated by Django 2.2.dev20180901131418 on 2018-09-22 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20180922_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_balance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='sharinggroup',
            name='users',
        ),
        migrations.AlterField(
            model_name='sharingspending',
            name='paying_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SharingInfo'),
        ),
        migrations.DeleteModel(
            name='SharingUserBalance',
        ),
        migrations.AddField(
            model_name='sharinginfo',
            name='sharing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SharingGroup'),
        ),
        migrations.AddField(
            model_name='sharinginfo',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
