# Generated by Django 2.2.dev20180901131418 on 2018-09-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180922_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharinginfo',
            old_name='users',
            new_name='user',
        ),
    ]
