# Generated by Django 2.2.dev20180901131418 on 2018-09-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180922_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingspending',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
