# Generated by Django 2.0.7 on 2018-09-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180922_1459'),
        ('core', '0014_auto_20180922_1612'),
    ]

    operations = [
    ]
