# Generated by Django 2.0.7 on 2018-09-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20180922_1659'),
        ('core', '0016_merge_20180922_1624'),
    ]

    operations = [
    ]
