# Generated by Django 2.2.dev20180901131418 on 2018-09-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20180922_1831'),
        ('core', '0016_sharingspending_description'),
    ]

    operations = [
    ]
